[package]
name = "telegram1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winping = { version = "0.10.1", features = ["full"] }
curl = "0.4.44"
urlencoding = "2.1.2"
